# Tool from https://github.com/romancitodev/simple-commits

[git]
skip_preview = true
skip_emojis = true

[[scopes]]
name = "app"
description = "The app layer changes"

[[scopes]]
name = "build"
description = "Build and Deploy related"

[[scopes]]
name = "deps"
description = "NodeJs packages deps"
