name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    ignore_paths:
      - ".eslintrc.json"
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Deps
        run: npm i

      - name: Build
        run: npm run "pages:build"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        # env:
          # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
          # YOUR_OTHER_SECRET: ${{ secrets.YOUR_OTHER_SECRET }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
          # secrets: |
          #   YOUR_SECRET
          #   YOUR_OTHER_SECRET
