#################### 🚧 WARNING: READ THIS BEFORE USING THIS FILE 🚧 ####################
#
#
#
# IF YOU DON'T KNOW WHAT YOU'RE DOING, YOU CAN EASILY LEAK SECRETS BY USING A
# `pull_request_target` WORKFLOW INSTEAD OF `pull_request`! SERIOUSLY, DO NOT
# BLINDLY COPY AND PASTE THIS FILE WITHOUT UNDERSTANDING THE FULL IMPLICATIONS
# OF WHAT YOU'RE DOING! WE HAVE TESTED THIS FOR OUR OWN USE CASES, WHICH ARE
# NOT NECESSARILY THE SAME AS YOURS! WHILE WE AREN'T EXPOSING ANY OF OUR SECRETS,
# ONE COULD EASILY DO SO BY MODIFYING OR ADDING A STEP TO THIS WORKFLOW!
#
#
#
#################### 🚧 WARNING: READ THIS BEFORE USING THIS FILE 🚧 ####################

name: Preview Deployment
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - closed

# cancel in-progress runs on new commits to same PR (github.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: ${{ github.event.action != 'closed' }}
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Workers
    env:
      WORKER_NAME: dashboard-pr-${{ github.event.pull_request.number }}
      ACTION_RUN: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Create comment
        id: comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body: |
            ## ⚡ Cloudflare Workers Preview
            | Name | Status |
            | :--- | :----- |
            | ${{env.WORKER_NAME}} | 🔨 Building ([Logs](${{env.ACTION_RUN}})) |

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        env:
          AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
          ADMINS: ${{ secrets.ADMINS }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '4.19.1'
          command: deploy --name "${{ env.WORKER_NAME }}"
          secrets: |
            ADMINS
            AUTH_GITHUB_ID
            AUTH_GITHUB_SECRET
            AUTH_SECRET
            AUTH_TRUST_HOST

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ## ⚡ Cloudflare Workers Preview
            | Name | Status | Preview |
            | :--- | :----- | :------ |
            | ${{env.WORKER_NAME}} | ✅ Ready ([Logs](${{env.ACTION_RUN}})) | ${{ steps.deploy.outputs.deployment-url }} |
